export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ESTATE_ADMIN = 'ESTATE_ADMIN',
  RESIDENT = 'RESIDENT',
  GUARD = 'GUARD'
}

export enum PassCodeType {
  GUEST = 'GUEST', // Expires 6 hrs or 1 use
  DOMESTIC = 'DOMESTIC' // Expires 6 months, renewable
}

export interface User {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  estateId?: string; // Null for Super Admin
  houseNumber?: string; // For Residents
  phone?: string;
  authorizedPhones?: AuthorizedPhone[]; // For Residents (Max 2)
}

export interface AuthorizedPhone {
  id: string;
  number: string;
  name: string; // Who owns this number
  status: 'PENDING' | 'APPROVED' | 'REJECTED';
}

export interface Estate {
  id: string;
  name: string;
  address: string;
  adminId: string;
}

export interface PassCode {
  id: string;
  code: string;
  residentId: string;
  estateId: string;
  type: PassCodeType;
  guestName: string;
  createdAt: number; // timestamp
  expiresAt: number; // timestamp
  isUsed: boolean; // Relevant for Guests
  generatedByPhone?: string; // If generated by auth phone
}

export interface AccessLog {
  id: string;
  passCodeId: string;
  passCodeType: PassCodeType;
  residentName: string;
  houseNumber: string;
  guestName: string;
  timestamp: number;
  estateId: string;
  status: 'ALLOWED' | 'DENIED';
  details?: string;
}

export interface AppState {
  currentUser: User | null;
  users: User[];
  estates: Estate[];
  passCodes: PassCode[];
  logs: AccessLog[];
}